/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Musixmatch API
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.kmozcan1.lyricquizapp.data.api.musixmatch

import com.kmozcan1.lyricquizapp.data.apimodel.InlineResponse2001
import com.kmozcan1.lyricquizapp.data.apimodel.InlineResponse2003
import io.reactivex.rxjava3.core.Single
import retrofit2.http.GET
import retrofit2.http.Headers
import java.math.BigDecimal

@JvmSuppressWildcards
interface AlbumApi {
    /**
     * 
     * 
     * The endpoint is owned by defaultname service owner
     * @param albumId The musiXmatch album id (required)
     * @param format output format: json, jsonp, xml. (optional, default to json)
     * @param callback jsonp callback (optional)
     */
    @Headers(
        "Content-Type: application/json"
    )
    @GET("album.get")
    fun albumGetGet(
        @retrofit2.http.Query("album_id") albumId: String,
        @retrofit2.http.Query("format") format: String?,
        @retrofit2.http.Query("callback") callback: String?
    ): Single<InlineResponse2001>
    /**
     * 
     * 
     * The endpoint is owned by defaultname service owner
     * @param artistId The musiXmatch artist id (required)
     * @param format output format: json, jsonp, xml. (optional, default to json)
     * @param callback jsonp callback (optional)
     * @param sReleaseDate Sort by release date (asc|desc) (optional)
     * @param gAlbumName Group by Album Name (optional)
     * @param pageSize Define the page size for paginated results.Range is 1 to 100. (optional)
     * @param page Define the page number for paginated results (optional)
     */
    @Headers(
        "Content-Type: application/json"
    )
    @GET("artist.albums.get")
    fun artistAlbumsGetGet(
        @retrofit2.http.Query("artist_id") artistId: String,
        @retrofit2.http.Query("format") format: String?,
        @retrofit2.http.Query("callback") callback: String?,
        @retrofit2.http.Query("s_release_date") sReleaseDate: String?,
        @retrofit2.http.Query("g_album_name") gAlbumName: String?,
        @retrofit2.http.Query("page_size") pageSize: BigDecimal?,
        @retrofit2.http.Query("page") page: BigDecimal?
    ): Single<InlineResponse2003>
}
