/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Musixmatch API
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.kmozcan1.lyricquizapp.data.api.musixmatch

import com.kmozcan1.lyricquizapp.domain.model.apimodel.InlineResponse20010
import com.kmozcan1.lyricquizapp.domain.model.apimodel.InlineResponse2002
import com.kmozcan1.lyricquizapp.domain.model.apimodel.InlineResponse2004
import io.reactivex.rxjava3.core.Single
import java.math.BigDecimal
import retrofit2.http.GET
import retrofit2.http.Headers

@JvmSuppressWildcards
interface ArtistApi {
    /**
     * 
     * 
     * The endpoint is owned by defaultname service owner
     * @param artistId  The musiXmatch artist id (required)
     * @param format output format: json, jsonp, xml. (optional, default to json)
     * @param callback jsonp callback (optional)
     */
    @Headers(
        "Content-Type: application/json"
    )
    @GET("artist.get")
    fun artistGetGet(
        @retrofit2.http.Query("artist_id") artistId: String,
        @retrofit2.http.Query("format") format: String?,
        @retrofit2.http.Query("callback") callback: String?
    ): Single<InlineResponse2004>
    /**
     * 
     * 
     * The endpoint is owned by defaultname service owner
     * @param artistId The musiXmatch artist id (required)
     * @param format output format: json, jsonp, xml. (optional, default to json)
     * @param callback jsonp callback (optional)
     * @param pageSize Define the page size for paginated results.Range is 1 to 100. (optional)
     * @param page Define the page number for paginated results (optional)
     */
    @Headers(
        "Content-Type: application/json"
    )
    @GET("artist.related.get")
    fun artistRelatedGetGet(
        @retrofit2.http.Query("artist_id") artistId: String,
        @retrofit2.http.Query("format") format: String?,
        @retrofit2.http.Query("callback") callback: String?,
        @retrofit2.http.Query("page_size") pageSize: BigDecimal?,
        @retrofit2.http.Query("page") page: BigDecimal?
    ): Single<InlineResponse2002>
    /**
     * 
     * 
     * The endpoint is owned by defaultname service owner
     * @param format output format: json, jsonp, xml. (optional, default to json)
     * @param callback jsonp callback (optional)
     * @param qArtist The song artist (optional)
     * @param fArtistId When set, filter by this artist id (optional)
     * @param page Define the page number for paginated results (optional)
     * @param pageSize Define the page size for paginated results.Range is 1 to 100. (optional)
     */
    @Headers(
        "Content-Type: application/json"
    )
    @GET("artist.search")
    fun artistSearchGet(
        @retrofit2.http.Query("format") format: String?,
        @retrofit2.http.Query("callback") callback: String?,
        @retrofit2.http.Query("q_artist") qArtist: String?,
        @retrofit2.http.Query("f_artist_id") fArtistId: BigDecimal?,
        @retrofit2.http.Query("page") page: BigDecimal?,
        @retrofit2.http.Query("page_size") pageSize: BigDecimal?
    ): Single<InlineResponse2002>
    /**
     * 
     * 
     * The endpoint is owned by defaultname service owner
     * @param format output format: json, jsonp, xml. (optional, default to json)
     * @param callback jsonp callback (optional)
     * @param page Define the page number for paginated results (optional)
     * @param pageSize Define the page size for paginated results.Range is 1 to 100. (optional)
     * @param country A valid ISO 3166 country code (optional, default to us)
     */
    @Headers(
        "Content-Type: application/json"
    )
    @GET("chart.artists.get")
    fun chartArtistsGetGet(
        @retrofit2.http.Query("format") format: String?,
        @retrofit2.http.Query("callback") callback: String?,
        @retrofit2.http.Query("page") page: BigDecimal?,
        @retrofit2.http.Query("page_size") pageSize: BigDecimal?,
        @retrofit2.http.Query("country") country: String?
    ): Single<InlineResponse20010>
}
