/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Musixmatch API
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.kmozcan1.lyricquizapp.data.api.musixmatch

import com.kmozcan1.lyricquizapp.data.apimodel.InlineResponse2007
import io.reactivex.rxjava3.core.Single
import retrofit2.http.GET
import retrofit2.http.Headers
import retrofit2.http.Query

@JvmSuppressWildcards
interface LyricsApi {
    /**
     * 
     * 
     * The endpoint is owned by defaultname service owner
     * @param trackId The musiXmatch track id (required)
     */
    @Headers(
        "Content-Type: application/json"
    )
    @GET("track.lyrics.get")
    fun trackLyricsGetGet(
        @retrofit2.http.Query("track_id") trackId: String,
        @Query("apikey") apiKey: String?
    ): Single<InlineResponse2007>
}
