/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Musixmatch API
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.kmozcan1.lyricquizapp.data.api.musixmatch

import com.kmozcan1.lyricquizapp.data.apimodel.InlineResponse2008
import io.reactivex.rxjava3.core.Single
import retrofit2.http.GET
import retrofit2.http.Headers

@JvmSuppressWildcards
interface SnippetApi {
    /**
     * 
     * 
     * The endpoint is owned by defaultname service owner
     * @param trackId The musiXmatch track id (required)
     * @param format output format: json, jsonp, xml. (optional, default to json)
     * @param callback jsonp callback (optional)
     */
    @Headers(
        "Content-Type: application/json"
    )
    @GET("track.snippet.get")
    fun trackSnippetGetGet(
        @retrofit2.http.Query("track_id") trackId: String,
        @retrofit2.http.Query("format") format: String?,
        @retrofit2.http.Query("callback") callback: String?
    ): Single<InlineResponse2008>
}
