/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Musixmatch API
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.kmozcan1.lyricquizapp.data.api.musixmatch

import com.kmozcan1.lyricquizapp.data.apimodel.InlineResponse2005
import io.reactivex.rxjava3.core.Single
import java.math.BigDecimal
import retrofit2.http.GET
import retrofit2.http.Headers

@JvmSuppressWildcards
interface SubtitleApi {
    /**
     * 
     * 
     * The endpoint is owned by defaultname service owner
     * @param format output format: json, jsonp, xml. (optional, default to json)
     * @param callback jsonp callback (optional)
     * @param qTrack The song title (optional)
     * @param qArtist  The song artist (optional)
     * @param fSubtitleLength Filter by subtitle length in seconds (optional)
     * @param fSubtitleLengthMaxDeviation Max deviation for a subtitle length in seconds (optional)
     */
    @Headers(
        "Content-Type: application/json"
    )
    @GET("matcher.subtitle.get")
    fun matcherSubtitleGetGet(
        @retrofit2.http.Query("format") format: String?,
        @retrofit2.http.Query("callback") callback: String?,
        @retrofit2.http.Query("q_track") qTrack: String?,
        @retrofit2.http.Query("q_artist") qArtist: String?,
        @retrofit2.http.Query("f_subtitle_length") fSubtitleLength: BigDecimal?,
        @retrofit2.http.Query("f_subtitle_length_max_deviation") fSubtitleLengthMaxDeviation: BigDecimal?
    ): Single<InlineResponse2005>
    /**
     * 
     * 
     * The endpoint is owned by defaultname service owner
     * @param trackId The musiXmatch track id (required)
     * @param format output format: json, jsonp, xml. (optional, default to json)
     * @param callback jsonp callback (optional)
     */
    @Headers(
        "Content-Type: application/json"
    )
    @GET("track.subtitle.get")
    fun trackSubtitleGetGet(
        @retrofit2.http.Query("track_id") trackId: String,
        @retrofit2.http.Query("format") format: String?,
        @retrofit2.http.Query("callback") callback: String?
    ): Single<InlineResponse2005>
}
