/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Musixmatch API
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.kmozcan1.lyricquizapp.data.api.musixmatch

import com.kmozcan1.lyricquizapp.data.apimodel.InlineResponse2009
import io.reactivex.rxjava3.core.Single
import java.math.BigDecimal
import retrofit2.http.GET
import retrofit2.http.Headers
import retrofit2.http.Query

@JvmSuppressWildcards
interface TrackApi {
    @Headers(
        "Content-Type: application/json"
    )
    @GET("chart.tracks.get")
    fun chartTracksGetGet(
        @Query("format") format: String?,
        @Query("callback") callback: String?,
        @Query("page") page: BigDecimal?,
        @Query("page_size") pageSize: BigDecimal?,
        @Query("country") country: String?,
        @Query("f_has_lyrics") fHasLyrics: String?,
        @Query("apikey") apiKey: String?
    ): Single<InlineResponse2009>
}
