/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Musixmatch API
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.kmozcan1.lyricquizapp.data.apimodel

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * @property language 
 * @property translation 
 */
@JsonClass(generateAdapter = true)
data class ArtistArtistNameTranslation(
    @Json(name = "language") @field:Json(name = "language") var language: String? = null,
    @Json(name = "translation") @field:Json(name = "translation") var translation: String? = null
)
