/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Musixmatch API
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.kmozcan1.lyricquizapp.data.apimodel

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * @property artistNameTranslation
 */
@JsonClass(generateAdapter = true)
data class ArtistArtistNameTranslationList(
    @Json(name = "artist_name_translation") @field:Json(name = "artist_name_translation") var artistNameTranslation: ArtistArtistNameTranslation? = null
)
