/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Musixmatch API
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.kmozcan1.lyricquizapp.data.apimodel

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * @property lyrics
 */
@JsonClass(generateAdapter = true)
data class InlineResponse2007MessageBody(
    @Json(name = "lyrics") @field:Json(name = "lyrics") var lyrics: ALyricsObject? = null
)
