/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Musixmatch API
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.kmozcan1.lyricquizapp.data.apimodel

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * @property message
 */
@JsonClass(generateAdapter = true)
data class InlineResponse2001(
    @Json(name = "message") @field:Json(name = "message") var message: InlineResponse2001Message? = null
)
