/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Musixmatch API
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.kmozcan1.lyricquizapp.domain.model.apimodel

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass
import java.math.BigDecimal

/**
 * a album of songs in the Musixmatch database.
 * @property albumCoverart500x500 
 * @property restricted 
 * @property artistId 
 * @property albumName 
 * @property albumCoverart800x800 
 * @property albumCopyright 
 * @property albumCoverart350x350 
 * @property artistName 
 * @property primaryGenres
 * @property albumId 
 * @property albumRating 
 * @property albumPline 
 * @property albumTrackCount 
 * @property albumReleaseType 
 * @property albumReleaseDate 
 * @property albumEditUrl 
 * @property updatedTime 
 * @property secondaryGenres
 * @property albumMbid 
 * @property albumVanityId 
 * @property albumCoverart100x100 
 * @property albumLabel 
 */
@JsonClass(generateAdapter = true)
data class AAlbumObject(
    @Json(name = "album_coverart_500x500") @field:Json(name = "album_coverart_500x500") var albumCoverart500x500: String? = null,
    @Json(name = "restricted") @field:Json(name = "restricted") var restricted: BigDecimal? = null,
    @Json(name = "artist_id") @field:Json(name = "artist_id") var artistId: BigDecimal? = null,
    @Json(name = "album_name") @field:Json(name = "album_name") var albumName: String? = null,
    @Json(name = "album_coverart_800x800") @field:Json(name = "album_coverart_800x800") var albumCoverart800x800: String? = null,
    @Json(name = "album_copyright") @field:Json(name = "album_copyright") var albumCopyright: String? = null,
    @Json(name = "album_coverart_350x350") @field:Json(name = "album_coverart_350x350") var albumCoverart350x350: String? = null,
    @Json(name = "artist_name") @field:Json(name = "artist_name") var artistName: String? = null,
    @Json(name = "primary_genres") @field:Json(name = "primary_genres") var primaryGenres: AlbumPrimaryGenres? = null,
    @Json(name = "album_id") @field:Json(name = "album_id") var albumId: BigDecimal? = null,
    @Json(name = "album_rating") @field:Json(name = "album_rating") var albumRating: BigDecimal? = null,
    @Json(name = "album_pline") @field:Json(name = "album_pline") var albumPline: String? = null,
    @Json(name = "album_track_count") @field:Json(name = "album_track_count") var albumTrackCount: BigDecimal? = null,
    @Json(name = "album_release_type") @field:Json(name = "album_release_type") var albumReleaseType: String? = null,
    @Json(name = "album_release_date") @field:Json(name = "album_release_date") var albumReleaseDate: String? = null,
    @Json(name = "album_edit_url") @field:Json(name = "album_edit_url") var albumEditUrl: String? = null,
    @Json(name = "updated_time") @field:Json(name = "updated_time") var updatedTime: String? = null,
    @Json(name = "secondary_genres") @field:Json(name = "secondary_genres") var secondaryGenres: ArtistSecondaryGenres? = null,
    @Json(name = "album_mbid") @field:Json(name = "album_mbid") var albumMbid: String? = null,
    @Json(name = "album_vanity_id") @field:Json(name = "album_vanity_id") var albumVanityId: String? = null,
    @Json(name = "album_coverart_100x100") @field:Json(name = "album_coverart_100x100") var albumCoverart100x100: String? = null,
    @Json(name = "album_label") @field:Json(name = "album_label") var albumLabel: String? = null
)
