/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Musixmatch API
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.kmozcan1.lyricquizapp.domain.model.apimodel

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass
import java.math.BigDecimal

/**
 * a artist in the Musixmatch database.
 * @property artistCredits
 * @property artistMbid 
 * @property artistName 
 * @property secondaryGenres
 * @property artistAliasList
 * @property artistVanityId 
 * @property restricted 
 * @property artistCountry 
 * @property artistComment 
 * @property artistNameTranslationList
 * @property artistEditUrl 
 * @property artistShareUrl 
 * @property artistId 
 * @property updatedTime 
 * @property managed 
 * @property primaryGenres
 * @property artistTwitterUrl 
 * @property artistRating 
 */
@JsonClass(generateAdapter = true)
data class AArtistObject(
    @Json(name = "artist_credits") @field:Json(name = "artist_credits") var artistCredits: ArtistArtistCredits? = null,
    @Json(name = "artist_mbid") @field:Json(name = "artist_mbid") var artistMbid: String? = null,
    @Json(name = "artist_name") @field:Json(name = "artist_name") var artistName: String? = null,
    @Json(name = "secondary_genres") @field:Json(name = "secondary_genres") var secondaryGenres: ArtistSecondaryGenres? = null,
    @Json(name = "artist_alias_list") @field:Json(name = "artist_alias_list") var artistAliasList: List<ArtistArtistAliasList>? = null,
    @Json(name = "artist_vanity_id") @field:Json(name = "artist_vanity_id") var artistVanityId: String? = null,
    @Json(name = "restricted") @field:Json(name = "restricted") var restricted: BigDecimal? = null,
    @Json(name = "artist_country") @field:Json(name = "artist_country") var artistCountry: String? = null,
    @Json(name = "artist_comment") @field:Json(name = "artist_comment") var artistComment: String? = null,
    @Json(name = "artist_name_translation_list") @field:Json(name = "artist_name_translation_list") var artistNameTranslationList: List<ArtistArtistNameTranslationList>? = null,
    @Json(name = "artist_edit_url") @field:Json(name = "artist_edit_url") var artistEditUrl: String? = null,
    @Json(name = "artist_share_url") @field:Json(name = "artist_share_url") var artistShareUrl: String? = null,
    @Json(name = "artist_id") @field:Json(name = "artist_id") var artistId: BigDecimal? = null,
    @Json(name = "updated_time") @field:Json(name = "updated_time") var updatedTime: String? = null,
    @Json(name = "managed") @field:Json(name = "managed") var managed: BigDecimal? = null,
    @Json(name = "primary_genres") @field:Json(name = "primary_genres") var primaryGenres: ArtistPrimaryGenres? = null,
    @Json(name = "artist_twitter_url") @field:Json(name = "artist_twitter_url") var artistTwitterUrl: String? = null,
    @Json(name = "artist_rating") @field:Json(name = "artist_rating") var artistRating: BigDecimal? = null
)
