/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Musixmatch API
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.kmozcan1.lyricquizapp.domain.model.apimodel

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass
import java.math.BigDecimal

/**
 * a Lyrics in the Musixmatch database.
 * @property instrumental 
 * @property pixelTrackingUrl 
 * @property publisherList
 * @property lyricsLanguageDescription 
 * @property restricted 
 * @property updatedTime 
 * @property explicit 
 * @property lyricsCopyright 
 * @property htmlTrackingUrl 
 * @property lyricsLanguage 
 * @property scriptTrackingUrl 
 * @property verified 
 * @property lyricsBody 
 * @property lyricsId 
 * @property writerList
 * @property canEdit 
 * @property actionRequested 
 * @property locked 
 */
@JsonClass(generateAdapter = true)
data class ALyricsObject(
    @Json(name = "instrumental") @field:Json(name = "instrumental") var instrumental: BigDecimal? = null,
    @Json(name = "pixel_tracking_url") @field:Json(name = "pixel_tracking_url") var pixelTrackingUrl: String? = null,
    @Json(name = "publisher_list") @field:Json(name = "publisher_list") var publisherList: List<String>? = null,
    @Json(name = "lyrics_language_description") @field:Json(name = "lyrics_language_description") var lyricsLanguageDescription: String? = null,
    @Json(name = "restricted") @field:Json(name = "restricted") var restricted: BigDecimal? = null,
    @Json(name = "updated_time") @field:Json(name = "updated_time") var updatedTime: String? = null,
    @Json(name = "explicit") @field:Json(name = "explicit") var explicit: BigDecimal? = null,
    @Json(name = "lyrics_copyright") @field:Json(name = "lyrics_copyright") var lyricsCopyright: String? = null,
    @Json(name = "html_tracking_url") @field:Json(name = "html_tracking_url") var htmlTrackingUrl: String? = null,
    @Json(name = "lyrics_language") @field:Json(name = "lyrics_language") var lyricsLanguage: String? = null,
    @Json(name = "script_tracking_url") @field:Json(name = "script_tracking_url") var scriptTrackingUrl: String? = null,
    @Json(name = "verified") @field:Json(name = "verified") var verified: BigDecimal? = null,
    @Json(name = "lyrics_body") @field:Json(name = "lyrics_body") var lyricsBody: String? = null,
    @Json(name = "lyrics_id") @field:Json(name = "lyrics_id") var lyricsId: BigDecimal? = null,
    @Json(name = "writer_list") @field:Json(name = "writer_list") var writerList: List<String>? = null,
    @Json(name = "can_edit") @field:Json(name = "can_edit") var canEdit: BigDecimal? = null,
    @Json(name = "action_requested") @field:Json(name = "action_requested") var actionRequested: String? = null,
    @Json(name = "locked") @field:Json(name = "locked") var locked: BigDecimal? = null
)
