/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Musixmatch API
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.kmozcan1.lyricquizapp.domain.model.apimodel

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * @property artistAlias 
 */
@JsonClass(generateAdapter = true)
data class ArtistArtistAliasList(
    @Json(name = "artist_alias") @field:Json(name = "artist_alias") var artistAlias: String? = null
)
