/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Musixmatch API
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.kmozcan1.lyricquizapp.domain.model.apimodel

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * @property artistList
 */
@JsonClass(generateAdapter = true)
data class ArtistArtistCredits(
    @Json(name = "artist_list") @field:Json(name = "artist_list") var artistList: List<String>? = null
)
