/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Musixmatch API
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.kmozcan1.lyricquizapp.domain.model.apimodel

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass
import java.math.BigDecimal

/**
 * Snippet of lyrics text in the Musixmatch database.
 * @property htmlTrackingUrl 
 * @property instrumental 
 * @property restricted 
 * @property updatedTime 
 * @property snippetBody 
 * @property pixelTrackingUrl 
 * @property snippetId 
 * @property scriptTrackingUrl 
 * @property snippetLanguage 
 */
@JsonClass(generateAdapter = true)
data class ASnippetObject(
    @Json(name = "html_tracking_url") @field:Json(name = "html_tracking_url") var htmlTrackingUrl: String? = null,
    @Json(name = "instrumental") @field:Json(name = "instrumental") var instrumental: BigDecimal? = null,
    @Json(name = "restricted") @field:Json(name = "restricted") var restricted: BigDecimal? = null,
    @Json(name = "updated_time") @field:Json(name = "updated_time") var updatedTime: String? = null,
    @Json(name = "snippet_body") @field:Json(name = "snippet_body") var snippetBody: String? = null,
    @Json(name = "pixel_tracking_url") @field:Json(name = "pixel_tracking_url") var pixelTrackingUrl: String? = null,
    @Json(name = "snippet_id") @field:Json(name = "snippet_id") var snippetId: BigDecimal? = null,
    @Json(name = "script_tracking_url") @field:Json(name = "script_tracking_url") var scriptTrackingUrl: String? = null,
    @Json(name = "snippet_language") @field:Json(name = "snippet_language") var snippetLanguage: String? = null
)
