/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Musixmatch API
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.kmozcan1.lyricquizapp.domain.model.apimodel

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass
import java.math.BigDecimal

/**
 * a synchronized lyrics subtitle in the Musixmatch database.
 * @property subtitleBody 
 * @property publisherList
 * @property subtitleLanguage 
 * @property subtitleLanguageDescription 
 * @property subtitleId 
 * @property pixelTrackingUrl 
 * @property htmlTrackingUrl 
 * @property restricted 
 * @property lyricsCopyright 
 * @property scriptTrackingUrl 
 * @property subtitleLength 
 * @property updatedTime 
 * @property writerList
 */
@JsonClass(generateAdapter = true)
data class ASubtitleObject(
    @Json(name = "subtitle_body") @field:Json(name = "subtitle_body") var subtitleBody: String? = null,
    @Json(name = "publisher_list") @field:Json(name = "publisher_list") var publisherList: List<String>? = null,
    @Json(name = "subtitle_language") @field:Json(name = "subtitle_language") var subtitleLanguage: String? = null,
    @Json(name = "subtitle_language_description") @field:Json(name = "subtitle_language_description") var subtitleLanguageDescription: String? = null,
    @Json(name = "subtitle_id") @field:Json(name = "subtitle_id") var subtitleId: BigDecimal? = null,
    @Json(name = "pixel_tracking_url") @field:Json(name = "pixel_tracking_url") var pixelTrackingUrl: String? = null,
    @Json(name = "html_tracking_url") @field:Json(name = "html_tracking_url") var htmlTrackingUrl: String? = null,
    @Json(name = "restricted") @field:Json(name = "restricted") var restricted: BigDecimal? = null,
    @Json(name = "lyrics_copyright") @field:Json(name = "lyrics_copyright") var lyricsCopyright: String? = null,
    @Json(name = "script_tracking_url") @field:Json(name = "script_tracking_url") var scriptTrackingUrl: String? = null,
    @Json(name = "subtitle_length") @field:Json(name = "subtitle_length") var subtitleLength: BigDecimal? = null,
    @Json(name = "updated_time") @field:Json(name = "updated_time") var updatedTime: String? = null,
    @Json(name = "writer_list") @field:Json(name = "writer_list") var writerList: List<String>? = null
)
