/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Musixmatch API
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.kmozcan1.lyricquizapp.domain.model.apimodel

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass
import java.math.BigDecimal

@JsonClass(generateAdapter = true)
data class ATrackObject(
    @Json(name = "artist_name") var artistName: String? = null,
    @Json(name = "artist_id") var artistId: BigDecimal? = null,
    @Json(name = "track_id") var trackId: BigDecimal? = null,
    @Json(name = "lyrics_id") var lyricsId: BigDecimal? = null
    )
