/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Musixmatch API
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.kmozcan1.lyricquizapp.domain.model.apimodel

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * @property albumList A list of albums
 */
@JsonClass(generateAdapter = true)
data class InlineResponse2003MessageBody(
    @Json(name = "album_list") @field:Json(name = "album_list") var albumList: List<InlineResponse2001MessageBody>? = null
)
