/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Musixmatch API
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.kmozcan1.lyricquizapp.domain.model.apimodel

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass
import java.math.BigDecimal

/**
 * @property statusCode 
 * @property available 
 * @property executeTime 
 */
@JsonClass(generateAdapter = true)
data class InlineResponse200MessageHeader(
    @Json(name = "status_code") @field:Json(name = "status_code") var statusCode: BigDecimal? = null,
    @Json(name = "available") @field:Json(name = "available") var available: BigDecimal? = null,
    @Json(name = "execute_time") @field:Json(name = "execute_time") var executeTime: BigDecimal? = null
)
