/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Musixmatch API
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.kmozcan1.lyricquizapp.domain.model.apimodel

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * @property header
 * @property body
 */
@JsonClass(generateAdapter = true)
data class InlineResponse2009Message(
    @Json(name = "header") @field:Json(name = "header") var header: InlineResponse2009MessageHeader? = null,
    @Json(name = "body") @field:Json(name = "body") var body: InlineResponse2009MessageBody? = null
)
