/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Musixmatch API
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.kmozcan1.lyricquizapp.domain.model.apimodel

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * @property snippet
 */
@JsonClass(generateAdapter = true)
data class InlineResponse2008MessageBody(
    @Json(name = "snippet") @field:Json(name = "snippet") var snippet: ASnippetObject? = null
)
