/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Musixmatch API
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.kmozcan1.lyricquizapp.domain.model.apimodel

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass
import java.math.BigDecimal

/**
 * @property musicGenreVanity 
 * @property musicGenreNameExtended 
 * @property musicGenreName 
 * @property musicGenreParentId 
 * @property musicGenreId 
 */
@JsonClass(generateAdapter = true)
data class TrackPrimaryGenresMusicGenre(
    @Json(name = "music_genre_vanity") @field:Json(name = "music_genre_vanity") var musicGenreVanity: String? = null,
    @Json(name = "music_genre_name_extended") @field:Json(name = "music_genre_name_extended") var musicGenreNameExtended: String? = null,
    @Json(name = "music_genre_name") @field:Json(name = "music_genre_name") var musicGenreName: String? = null,
    @Json(name = "music_genre_parent_id") @field:Json(name = "music_genre_parent_id") var musicGenreParentId: BigDecimal? = null,
    @Json(name = "music_genre_id") @field:Json(name = "music_genre_id") var musicGenreId: BigDecimal? = null
)
