package com.kmozcan1.lyricquizapp.domain.interactor

import com.kmozcan1.lyricquizapp.domain.Constants
import com.kmozcan1.lyricquizapp.domain.Constants.MAX_CHART_PAGE_SIZE
import com.kmozcan1.lyricquizapp.domain.Constants.NUMBER_OF_TRACKS_TO_FETCH
import com.kmozcan1.lyricquizapp.domain.enumeration.Country
import com.kmozcan1.lyricquizapp.domain.interactor.base.FlowableUseCase
import com.kmozcan1.lyricquizapp.domain.mapper.TrackRepositoryToDomainModelMapper
import com.kmozcan1.lyricquizapp.domain.model.domainmodel.LyricsDomainModel
import com.kmozcan1.lyricquizapp.domain.model.domainmodel.TrackDomainModel
import com.kmozcan1.lyricquizapp.domain.repository.TrackRepository
import io.reactivex.rxjava3.core.Flowable
import io.reactivex.rxjava3.core.Single
import javax.inject.Inject

/**
 * Fetches tracks from the API and returns the questions generated by
 * Created by Kadir Mert Özcan on 17-Dec-20.
 */
class GetTracksFromApiUseCase @Inject constructor(
    private val trackRepository: TrackRepository,
    private val trackRepositoryToDomainModelMapper: TrackRepositoryToDomainModelMapper,
    ) : FlowableUseCase<List<TrackDomainModel>, GetTracksFromApiUseCase.Params>() {
    data class Params(
        val country: Country,
        val questionCount: Int
        )

    override fun buildObservable(params: Params?): Flowable<List<TrackDomainModel>> {
        val remainder = NUMBER_OF_TRACKS_TO_FETCH % MAX_CHART_PAGE_SIZE
        var apiCallCount = NUMBER_OF_TRACKS_TO_FETCH / MAX_CHART_PAGE_SIZE
        // Make last call for remainders if the number of tracks to fetch is not divisible to 100
        if (remainder != 0) {
            apiCallCount++
        }
        val pageSize = if (NUMBER_OF_TRACKS_TO_FETCH <= Constants.MAX_CHART_PAGE_SIZE) {
            NUMBER_OF_TRACKS_TO_FETCH
        } else {
            MAX_CHART_PAGE_SIZE
        }

        val taskList = mutableListOf<Single<List<TrackDomainModel>>>()

        for (page in 1..apiCallCount) {
            taskList.add(
                trackRepository.getTracksFromChart(params!!.country, pageSize, page)
                    .map { response ->
                        response?.mapNotNull {
                            trackRepositoryToDomainModelMapper.map(it.track)
                        }
                    }
            )
        }

        return Single.merge(taskList)
    }
}