package com.kmozcan1.lyricquizapp.domain.interactor

import com.kmozcan1.lyricquizapp.domain.enumeration.Country
import com.kmozcan1.lyricquizapp.domain.interactor.base.SingleUseCase
import com.kmozcan1.lyricquizapp.domain.mapper.TrackRepositoryToDomainModelMapper
import com.kmozcan1.lyricquizapp.domain.model.domainmodel.TrackDomainModel
import com.kmozcan1.lyricquizapp.domain.repository.TrackRepository
import io.reactivex.rxjava3.core.Single
import javax.inject.Inject

/**
 * Fetches tracks from the API and returns the questions generated by
 * Created by Kadir Mert Özcan on 17-Dec-20.
 */
class GetTracksFromChartUseCase @Inject constructor(
    private val trackRepository: TrackRepository,
    private val trackRepositoryToDomainModelMapper: TrackRepositoryToDomainModelMapper,
    ) : SingleUseCase<List<TrackDomainModel>, GetTracksFromChartUseCase.Params>() {
    data class Params(
        val country: Country,
        val questionCount: Int
        )

    override fun buildObservable(params: Params?): Single<List<TrackDomainModel>> {
        return trackRepository.getTracksFromChart(params!!.country, params.questionCount)
            .map { response ->
                response.mapNotNull { trackRepositoryToDomainModelMapper.map(it)
                }
            }
    }
}